import {SCENES,SAMPLES,RANKS,RANK_HINTS,sceneById,sampleById} from './content.js';
import {STORAGE_KEY,freshState,validateState,missionProgress,rankIndex,items,nextTask,taskDone,hasPhoto,hasSample,recordPhoto,recordSolarPhoto,recordWorldPhoto,usesDwarfArtwork,isSceneSubject,recordSample,removePhoto,PHOTO_LIMIT,unlockedComparisons} from './state.js';
import {icon} from './icons.js';
import {loadImage,renderSlide,createPdf} from './pdf.js';
import {defaultCamera,drawPhoto} from './camera.js';
import {mountFlight} from './flight.js';
import {mountSolarFlight,solarControls} from './solar-flight.js';
import {bodyById,nearestBody,visibleBody,length,sub,AU_KM,defaultSolar,eraConfig,approachPosition,lookAt} from './solar-system.js';
import {drawSolarPhoto,rendererReady} from './solar-renderer.js';
import {LESSONS,renderLessonFigure} from './curriculum.js';
import {recommendedSelection} from './presentation-support.js';
import {rubyText} from './reading-support.js';
import {createReadingController} from './reading-controller.js';
let flight=null,modalRevision=0;
const worldState=()=>state.flightMode==='solar'?state.solar:state.historySolar;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const modal=$('#modal');
const reader=createReadingController({engine:window.speechSynthesis,createUtterance:text=>new window.SpeechSynthesisUtterance(text),onStatus:({speaking})=>{
  modal.querySelectorAll('[data-action="speak"]').forEach(el=>{el.disabled=speaking;});
  modal.querySelectorAll('[data-action="stop-reading"]').forEach(el=>{el.hidden=!speaking;});
  modal.querySelectorAll('.reading-status').forEach(el=>{el.textContent=speaking?'読み上げ中':'';});
},onError:message=>toast(message,true)});
function readingControls(){return `<div class="reading-controls">${button('speak','この説明を聞く',null,'subtle small')}${button('stop-reading','読み上げを止める',null,'subtle small','hidden')}<span class="reading-status" role="status"></span></div>`;}
function readableText(root){
  const read=node=>{
    if(node.nodeType===Node.TEXT_NODE)return node.textContent;
    if(node.nodeType!==Node.ELEMENT_NODE||node.hidden||node.getAttribute('aria-hidden')==='true'||node.matches('rt,rp,button,svg,canvas,script,style,.reading-controls,.lesson-keywords,.fine'))return '';
    if(node.matches('details')&&!node.open)return '';
    const text=Array.from(node.childNodes,read).join('');
    return node.matches('p,li,h3,h4,div,summary')?`${text}\n`:text;
  };
  return root?read(root).replace(/[ \t]+/g,' ').replace(/\n+/g,'\n').trim():'';
}
let state=freshState(),view='ship',filter='photo',busy=false,pendingImport=null,skipAnimation=null,storageFailed=false,damagedSave=false,latestDownloadUrl=null;
try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)state=validateState(JSON.parse(saved));}catch{storageFailed=true;damagedSave=true;}
state.started=true;
function toast(message,error=false){const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=message;$('#toast-region').append(el);setTimeout(()=>el.remove(),4600);}
function save(){if(damagedSave)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageFailed=false;}catch{storageFailed=true;}updateWarning();}
function updateWarning(){let w=$('#save-warning');if(storageFailed){if(!w){w=document.createElement('div');w.id='save-warning';w.className='save-warning';w.setAttribute('role','status');$('.app-header').after(w);}w.textContent=damagedSave?'以前の探検データを読み込めませんでした。自動上書きを止めています。設定からデータを保存してください。':'このブラウザに記録を保存できません。設定の「探検データを保存」で記録を持ち出してください。';}else w?.remove();}
function sound(type='success'){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=type==='shutter'?700:520;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);o.start();o.stop(ctx.currentTime+.22);o.onended=()=>ctx.close();}catch{}}
function commit(fn,message){const rank=rankIndex(state),before=missionProgress(state),cards=unlockedComparisons(state).length;fn();save();render();if(message)toast(message);missionProgress(state).filter((m,i)=>m.complete&&!before[i].complete).forEach(m=>toast(`ミッション達成！「${m.badge}」`));if(unlockedComparisons(state).length>cards)toast('2つの時代がそろいました。比較カードが完成！');if(rankIndex(state)>rank)toast(`称号アップ！「${RANKS[rankIndex(state)]}」`);sound();}
function openModal(title,body,wide=false){reader.stop();modalRevision++;flight?.stop();$('#modal-content').innerHTML=`<div class="modal-header"><h2>${rubyText(title)}</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><div class="modal-body">${body}</div>`;modal.classList.toggle('wide',wide);if(!modal.open)modal.showModal();modal.scrollTop=0;hydratePhotoViews(modal);}
function closeModal(){reader.stop();modalRevision++;modal.close();}
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
modal.addEventListener('close',()=>reader.stop());
modal.addEventListener('toggle',event=>{if(event.target.matches('details'))reader.stop();},true);
window.addEventListener('pagehide',()=>reader.stop());
document.addEventListener('visibilitychange',()=>{if(document.hidden)reader.stop();});
const button=(action,label,ic,cls='subtle',extra='')=>`<button class="button ${cls}" data-action="${action}" ${extra}>${ic?icon(ic):''}${label}</button>`;
const kindName=kind=>({photo:'写真',sample:'サンプル',compare:'比較カード'}[kind]);
const dateText=value=>new Date(value).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
function render(){flight?.dispose();flight=null;document.body.classList.toggle('reduce-motion',state.reducedMotion);$('#navigation').innerHTML=[['ship','ship','船内'],['time','time','時代マップ'],['collection','collection','コレクション'],['presentation','pdf','発表']].map(([id,ic,label])=>`<button class="${view===id?'active':''}" data-view="${id}" ${view===id?'aria-current="page"':''}>${icon(ic)}${label}${id==='presentation'&&state.selected.length?`<span class="nav-count">${state.selected.length}</span>`:''}</button>`).join('');$('#rank-button').innerHTML=icon('star')+`<span>${RANKS[rankIndex(state)]}</span>`;$('#rank-button').setAttribute('aria-label',`称号：${RANKS[rankIndex(state)]}。5段階の称号を見る`);$('#settings-button').innerHTML=icon('settings');$('#main').innerHTML=({ship:renderShip,time:renderMap,collection:renderCollection,presentation:renderPresentation}[view])();updateWarning();hydratePhotoViews($('#main'));if(view==='ship'){const mountedState=state;if(usesDwarfArtwork(state)){flight=mountFlight($('.flight-zone'),{scene:sceneById(state.currentScene),camera:mountedState.camera,onChange:c=>{mountedState.camera=c;},onSave:save,blocked:()=>busy||modal.open,photograph,onError:m=>toast(m,true)});}else{const worldKey=state.flightMode==='solar'?'solar':'historySolar';flight=mountSolarFlight($('.solar-zone'),{state:mountedState[worldKey],onChange:s=>{mountedState[worldKey]=s;},onSave:save,blocked:()=>busy||modal.open,photograph,onMessage:toast,onError:m=>toast(m,true)});}}}
function navigate(target){if(!['ship','time','collection','presentation'].includes(target))return;reader.stop();view=target;render();window.scrollTo({top:0,behavior:'instant'});}
function renderMissionGuide(){const next=nextTask(state),complete=missionProgress(state).filter(m=>m.complete).length;return `<section class="mission-strip mission-guide" aria-label="次にすること">${icon('target')}<div class="content"><small>${next?`次の調査 ・ ${complete} / 3 ミッション達成`:'3つのミッションを達成しました'}</small><p>${next?rubyText(next.task.label):'発見を発表にまとめよう。'}</p></div>${next?button('next-task','調査地点へ','rocket','small'):button('presentation','発表をつくる','pdf','small')}${button('missions','調査ノート',null,'subtle small')}</section>`;}
function renderShip(){return usesDwarfArtwork(state)?renderHistoryShip():renderSolarShip();}
function renderHistoryShip(){const scene=sceneById(state.currentScene),complete=missionProgress(state).filter(m=>m.complete).length;return `<div class="page ship-page"><div class="page-heading"><div><p class="eyebrow">OBSERVATION DECK</p><h1>${rubyText(scene.name)}</h1></div><div class="row wrap">${button('dwarf-explore','この時代を360°探索','rocket','subtle small')}${button('curriculum','学習ノート 001〜010','info','subtle small')}${button('enter-solar','太陽系を360°飛ぶ','rocket','subtle small')}<button class="badge clickable" data-action="missions">調査 ${complete} / 3</button></div></div>
${renderMissionGuide()}<div class="flight-zone"><section class="cockpit" aria-label="宇宙船の窓と操縦パネル"><div class="flight-window"><canvas class="flight-canvas" tabindex="0" width="1280" height="720" aria-label="宇宙船の窓。ドラッグで見回す。WASDで前後左右、Eで上昇、Qで下降、矢印キーで視線を動かす。スペースで撮影。"></canvas></div><div class="scene-shade"></div><img class="cockpit-overlay" src="assets/cockpit.png" alt="" aria-hidden="true"><div class="scene-label"><span class="location-kicker">${scene.number} / 観測地点</span><h2>${rubyText(scene.name)}</h2><p>${scene.era}</p></div><span class="scene-tag">${scene.tag}</span><div class="cockpit-caption">${scene.summary}</div><div class="view-action">${button('album','アルバム','album','subtle small')}${button('samples','サンプル','collection','subtle small')}</div><div class="cockpit-controls"><button class="command" data-action="observe">${icon('eye')}<span>観察する</span></button><button class="command" data-action="photograph">${icon('camera')}<span>写真を撮る</span></button><button class="command" data-action="sample">${icon('sample')}<span>サンプル採取</span></button><button class="command" data-view="time">${icon('time')}<span>時代を選ぶ</span></button></div></section>
<p class="world-era-note">白色矮星と広がったガスの全景です。全景の中で視線や距離を調整できます。周囲へ飛び回るには「この時代を360°探索」を選びましょう。</p>${flightControls()}</div><div class="ship-bottom"><span id="ship-statistics">写真 ${state.photos.length}枚 ・ サンプル ${state.samples.length}点 ・ 画面表示 ${state.minutes}分</span><div class="row"><button data-action="missions">${icon('target')} 調査ノート</button><button data-action="shelf">${icon('collection')} 船内展示</button><button data-action="help">${icon('info')} 遊び方</button></div></div></div>`;}
function renderMap(){const next=nextTask(state);return `<div class="page"><div class="page-heading"><div><p class="eyebrow">TIME NAVIGATION</p><h1>どの時代へ、旅をしよう。</h1><p class="muted">すべての時代に自由に移動できます。</p></div>${button('missions','調査ノート','target')}</div><div class="era-legend"><span>過去</span><div></div><span>現在</span><div></div><span>未来</span></div><div class="scene-grid">${SCENES.map(s=>`<button class="scene-card ${state.currentScene===s.id?'current':''}" data-action="travel" data-scene="${s.id}"><div class="scene-card-image"><img src="${s.image}" alt="" loading="lazy"><span class="scene-number">${s.number}</span>${next?.task.scene===s.id?'<span class="recommend">次の調査</span>':''}</div><div class="scene-card-body"><span class="era">${s.era}</span><h2>${rubyText(s.name)}</h2><p>${s.summary}</p><div class="scene-card-footer"><span>${state.currentScene===s.id?'現在地':state.observed.includes(s.id)?'観察済み':'この時代へ'} ${icon('chevron')}</span><span class="scene-records">${hasPhoto(state,s.id)?icon('camera'):''}${state.samples.some(a=>sampleById(a.id).scene===s.id)?icon('sample'):''}</span></div></div></button>`).join('')}</div><p class="footnote">時代旅行と船の保護装置は架空の技術です。風景は科学に基づく再現・未来の予測です。年代や距離の間隔は模式的に示しています。</p></div>`;}
function photoArt(photo, name) {return `<canvas class="photo-frame" data-photo-id="${esc(photo.id)}" width="640" height="360" role="img" aria-label="${esc(name)}"></canvas>`;}
function hydratePhotoViews(root){for(const canvas of root.querySelectorAll('[data-photo-id]')){const photo=state.photos.find(p=>p.id===canvas.dataset.photoId);if(!photo)continue;if(photo.solar){rendererReady.then(()=>{if(canvas.isConnected)drawSolarPhoto(canvas.getContext('2d'),photo.solar,0,0,640,360);}).catch(e=>canvas.setAttribute('aria-label',e.message));continue;}loadImage(sceneById(photo.scene).image).then(image=>{if(canvas.isConnected)drawPhoto(canvas.getContext('2d'),image,photo.camera,0,0,640,360);}).catch(()=>{canvas.setAttribute('aria-label','写真を読み込めません。通信を確認してください。');});}}
function art(item,extra=''){if(item.kind==='compare')return `<div class="comparison-art ${extra}">${item.record.scenes.map((id,i)=>photoArt(item.record.photos[i],sceneById(id).name)).join('')}<span>${icon('compare')}</span></div>`;const sample=item.kind==='sample'?sampleById(item.record.id):null;return `<div class="record-art ${sample?.kind==='material'?'material':''} ${extra}">${item.kind==='photo'?photoArt(item.record,item.name):`<img src="${sample?.image||sceneById(item.scene).image}" alt="${esc(item.name)}" loading="lazy">`}${sample?.kind==='data'?'<span class="art-tag">観測データ</span>':''}</div>`;}
function flightControls(){const move=(id,label)=>`<button type="button" data-flight="${id}">${label}</button>`;return `<div class="flight-toolbar"><div><strong>自由操縦</strong><span>窓をドラッグして見回す</span></div><button type="button" data-flight-toggle aria-expanded="true" aria-controls="flight-panel">操縦パネル</button><button type="button" data-flight-reset>最初の位置に戻る</button></div><div class="flight-panel" id="flight-panel"><div class="flight-group"><span>船を移動 <small>押している間、移動</small></span><div class="flight-buttons">${move('left','← 左へ')}${move('forward','前進 W')}${move('right','右へ →')}${move('down','下降 Q')}${move('backward','後退 S')}${move('up','上昇 E')}</div></div><div class="flight-group camera-group"><span>カメラの向き</span><div class="flight-buttons">${move('look-left','左を見る')}${move('look-up','上を見る')}${move('look-right','右を見る')}${move('look-down','下を見る')}</div></div><div class="flight-guide"><p>窓をクリックしてから<br><kbd>W A S D</kbd> 前後左右・<kbd>Q E</kbd> 上下<br><kbd>↑ ↓ ← →</kbd> 見回す・<kbd>Space</kbd> 撮影</p><small>観測エリア内を自由に移動できます。<br>数値はゲーム内の位置の目安です。</small></div></div><output class="flight-status" aria-live="off" aria-label="船の位置とカメラの向き"></output>`;}

function recordCard(item){const selected=state.selected.includes(item.key),s=recordScene(item);return `<article class="record-card"><button class="record-open" data-action="detail" data-key="${item.key}" aria-label="${esc(item.name)}の詳細">${art(item)}<div class="record-title"><span class="era">${item.kind==='compare'?'2つの時代を比較':s.era}</span><h2>${rubyText(item.name)}</h2><p>${item.kind==='compare'?item.record.hint:item.kind==='sample'?sampleById(item.record.id).type:dateText(item.created)}</p></div></button><div class="record-card-footer">${button('toggle-select',selected?'選択済み':'発表に使う',selected?'check':'pdf',selected?'selected wide':'subtle wide',`data-key="${item.key}" aria-pressed="${selected}"`)}</div></article>`;}
function renderCollection(){const list=items(state).filter(item=>item.kind===filter);return `<div class="page"><div class="page-heading"><div><p class="eyebrow">EXPEDITION ARCHIVE</p><h1>旅の記録、わたしの発見。</h1><p class="muted">お気に入りを選んで、みんなに伝えよう。</p></div>${button('presentation',`発表に使う ${state.selected.length}件`,'pdf','')}</div><div class="collection-tabs" aria-label="コレクションの種類">${[['photo','写真',state.photos.length,'camera'],['sample','サンプル',state.samples.length,'sample'],['compare','比較カード',unlockedComparisons(state).length,'compare']].map(([id,label,count,ic])=>`<button aria-pressed="${filter===id}" class="${filter===id?'active':''}" data-filter="${id}">${icon(ic)}${label}<span>${count}</span></button>`).join('')}<button class="shelf-link" data-action="shelf">${icon('collection')}船内展示</button></div>${filter==='photo'&&state.photos.length>=PHOTO_LIMIT?'<p class="world-era-note">写真が60枚になりました。不要な写真の詳細を開き、「この写真を削除」で整理すると、新しい写真を撮れます。</p>':''}${list.length?`<div class="record-grid">${list.map(recordCard).join('')}</div>`:`<div class="empty">${icon(filter==='compare'?'compare':filter==='photo'?'camera':'sample')}<h2>${filter==='compare'?'2つの時代を、写真でつなごう。':filter==='photo'?'最初の一枚を、撮りに行こう。':'最初のサンプルを、見つけよう。'}</h2><p>${filter==='compare'?'「誕生期と現在の地球」または「現在と未来の太陽」を撮影すると完成します。':'船内の操作パネルから記録できます。'}</p>${button('ship','船内へ戻る','ship','')}</div>`}${filter==='compare'?'<p class="footnote">撮影済みの写真から自動で完成します。写真の撮影距離は異なるため、太陽の大きさは詳細画面の補助図で比べましょう。</p>':''}</div>`;}
function selectedItems(){const all=items(state);return state.selected.map(key=>all.find(i=>i.key===key)).filter(Boolean);}
function renderPresentation(){const selected=selectedItems(),recommended=selected.length?[]:recommendedSelection(state);return `<div class="page"><div class="page-heading"><div><p class="eyebrow">SHARE YOUR DISCOVERIES</p><h1>発見を、だれかに届けよう。</h1><p class="muted">写真やサンプルを並べて、手書き欄付きのPDFを作成します。</p></div>${button('collection','記録を追加','collection')}</div><div class="presentation-layout"><div>${selected.length?`<div class="slide-list">${selected.map((item,i)=>`<article class="slide-row"><span class="slide-number">${String(i+1).padStart(2,'0')}</span>${art(item,'mini')}<div class="slide-edit"><label for="title-${i}">${kindName(item.kind)}の見出し</label><input id="title-${i}" data-title-key="${item.key}" maxlength="32" value="${esc(state.titles[item.key]||item.name)}"><button class="text-button" data-action="preview" data-key="${item.key}">${icon('eye')} このページを見る</button></div><div class="order-actions"><button class="icon-button" data-action="move-up" data-key="${item.key}" aria-label="${i+1}ページ目を上へ" ${i===0?'disabled':''}>${icon('up')}</button><button class="icon-button" data-action="move-down" data-key="${item.key}" aria-label="${i+1}ページ目を下へ" ${i===selected.length-1?'disabled':''}>${icon('down')}</button><button class="icon-button" data-action="remove-selected" data-key="${item.key}" aria-label="${i+1}ページ目を発表から外す">${icon('close')}</button></div></article>`).join('')}</div>`:`<div class="empty">${icon('pdf')}<h2>どの発見を紹介しよう？</h2><p>コレクションで「発表に使う」を押してください。<br>まずは3ページが目安。1ページから作れます。</p>${recommended.length?`<div class="recommendation"><p>写真・サンプル・比較カードから、まとめやすい候補を選びます。あとで差し替えられます。</p>${button('recommend-slides',`おすすめ${recommended.length}枚を選ぶ`,'star','')}</div>`:''}${button('collection','コレクションから選ぶ','collection','subtle')}</div>`}</div><aside class="export-panel"><span class="eyebrow">YOUR PRESENTATION</span><h2>わたしの宇宙調査</h2><div class="paper-mini" aria-hidden="true"><div class="paper-mini-header"></div><div class="paper-mini-body"><div></div><span><i></i><i></i><i></i></span></div></div><div class="export-count"><strong>${selected.length}</strong><span>ページ / A4 横</span></div><p>画像・時代・場所は自動で入ります。<br>気づきや考えは、自分の言葉や絵で。</p>${button('export-pdf','発表PDFを作成','download','wide',selected.length?'':'disabled')}<ol class="export-steps"><li>PDFをダウンロード</li><li>Chromebookの描画ツールで開く</li><li>白い欄に手書きして、保存・発表</li></ol><p class="fine">手書きしたあとのファイルも保存しよう。</p></aside></div></div>`;}

function showMissions(){openModal('3つの調査ミッション',`<div class="mission-list">${missionProgress(state).map((m,i)=>`<article class="mission-card ${m.complete?'completed':''}"><div class="row space-between"><span class="eyebrow">MISSION 0${i+1}</span><span class="badge">${m.complete?icon('check')+' 達成':`${m.count} / ${m.tasks.length}`}</span></div><h3>${rubyText(m.title)}</h3><p class="muted">${rubyText(m.description)}</p><ul class="task-list">${m.tasks.map(t=>`<li class="${taskDone(state,t)?'done':''}">${icon(taskDone(state,t)?'check':'target')}<span>${rubyText(t.label)}</span></li>`).join('')}</ul>${m.complete?`<p class="earned-badge">${icon('star')} ${m.badge}</p>`:button('choose-mission','この調査を進める','chevron','subtle',`data-mission="${m.id}"`)}</article>`).join('')}</div><p class="fine">順番は自由です。先に集めた記録も達成になります。</p>`);}
function showRanks(){const rank=rankIndex(state);openModal('調査員証',`<div class="rank-card"><div class="rank-seal">${icon('star')}</div><div><span class="eyebrow">LEVEL ${rank+1} / 5</span><h3>${RANKS[rank]}</h3><p class="muted">${rank===4?'きみの発見が、だれかの宇宙への入り口になる。':'発見を積み重ねて、宇宙の案内人へ。'}</p></div></div><ol class="rank-ladder">${RANKS.map((name,i)=>`<li class="${i<=rank?'achieved':''} ${i===rank?'current':''}"><span class="rank-level">${i<=rank?icon('check'):i+1}</span><div><strong>${name}</strong><small>${RANK_HINTS[i]}</small></div>${i===rank?'<span class="badge">現在</span>':''}</li>`).join('')}</ol><p class="fine">PDFはいつでも作れます。先に作った場合も記録され、3ミッションを終えたときに最後の称号がもらえます。</p>`);}
function showShelf(){openModal('船内の展示棚',`<p class="muted">旅で持ち帰った、${state.samples.length}点の発見。</p><div class="shelf-grid">${SAMPLES.map(s=>{const found=hasSample(state,s.id),item=items(state).find(i=>i.key===`sample:${s.id}`);return `<button class="shelf-slot ${found?'found':''}" data-action="${found?'detail':'travel'}" ${found?`data-key="sample:${s.id}"`:`data-scene="${s.scene}"`} aria-label="${s.name}${found?'の詳細':'を探しに行く'}">${found?art(item):`<div class="unknown-specimen">${icon(s.kind==='data'?'eye':'sample')}</div>`}<strong>${found?s.name:'未発見'}</strong><small>${found?s.type:sceneById(s.scene).name+'で探す'}</small></button>`;}).join('')}</div><div class="row wrap">${missionProgress(state).filter(m=>m.complete).map(m=>`<span class="badge">${icon('star')}${m.badge}</span>`).join('')}</div>`,true);}
function showDetail(key){const item=items(state).find(i=>i.key===key);if(!item)return;const sample=item.kind==='sample'?sampleById(item.record.id):null,scene=recordScene(item),selected=state.selected.includes(key);openModal(item.name,`${art(item,'detail-art')}<section data-reading-panel>${readingControls()}<div data-reading-content><p class="detail-meta">${item.kind==='compare'?'比較カード':scene.era+' / '+scene.location}</p><p>${rubyText(sample?.note||item.record.hint||scene.summary)}</p>${sample?`<p class="fine">${sample.method}による${sample.kind==='data'?'模擬観測の記録です。':'ゲーム内の模擬採集。画像は生成したイメージです。'}</p>`:''}</div></section>${item.kind==='compare'&&item.record.id==='sun-history'?`<div class="scale-illustration"><span class="tiny-sun"></span><span class="big-sun"></span><div>現在 = 1<span>赤色巨星：直径が数十〜数百倍<br>図は約100倍の例</span></div></div>`:''}<div class="row wrap">${button('detail-select',selected?'発表から外す':`この${item.kind==='photo'?'写真':item.kind==='sample'?'サンプル':'比較カード'}を発表に使う`,selected?'check':'pdf',selected?'subtle':'',`data-key="${key}"`)}${button('make-single','この記録でスライドを作る','chevron','subtle',`data-key="${key}"`)}${item.kind==='photo'?button('confirm-delete-photo','この写真を削除',null,'subtle',`data-key="${key}"`):''}</div>`);}
function toggleSelect(key){if(!items(state).some(i=>i.key===key))return;const n=state.selected.indexOf(key);if(n>=0)state.selected.splice(n,1);else{if(state.selected.length>=20){toast('発表は20ページまで選べます。',true);return;}state.selected.push(key);}save();render();}
function showSettings(){openModal('設定と探検データ',`<div class="setting-row"><div><strong>効果音</strong><p class="fine">撮影や達成を音で知らせます。</p></div><input aria-label="効果音を使う" type="checkbox" data-setting="sound" ${state.sound?'checked':''}></div><div class="setting-row"><div><strong>動きを少なくする</strong><p class="fine">移動や撮影の演出を短くします。</p></div><input aria-label="動きを少なくする" type="checkbox" data-setting="reducedMotion" ${state.reducedMotion?'checked':''}></div><section class="settings-section"><h3>次の授業へ、記録を持っていこう。</h3><p class="muted">写真・サンプル・称号・発表の選択を保存します。別の端末でも、このファイルを読み込めば続きから遊べます。</p><div class="row wrap">${button('export-data','探検データを保存','download','')}${button('import-data','データを読み込む','upload')}</div><p class="fine">通常はこのブラウザにも自動保存されます。ブラウザのデータを消す前に、ファイルを保存してください。</p></section><div class="row wrap">${button('help','遊び方・科学について','info')}${button('confirm-reset','新しい探検を始める',null)}</div>`);}
function showHelp(){openModal('旅のしおり',`<div class="help-steps"><div><strong>1. 時代を選ぶ</strong><p>「行き先を見る」で次の調査へ。寄り道も自由です。</p></div><div><strong>2. 自由に操縦して、撮影・採集</strong><p>窓をドラッグして見回し、操縦パネルやWASD・Q/Eキーで移動できます。太陽系360°では目的地を選び「光速で向かう」で飛行。「光速・実時間」と「光速・時間短縮」を選べます。時間短縮はスライダーで10〜100倍に調整でき、飛行中も変更できます。Xで停止できます。「最初の位置に戻る」で帰れます。好きな構図で写真を撮り、写真やサンプルを持ち帰りましょう。光は観測データとして記録します。</p></div><div><strong>3. 自分の発見を伝える</strong><p>コレクションで「発表に使う」を選び、PDFを作成。描画ツールで白い欄に書き込みます。</p></div></div><details><summary>先生へ・授業の進め方</summary><p>50分なら導入5分・探索30分・発表資料選びとPDF保存10分・データ保存5分が目安です。次の授業ではPDFに手書きし、発表します。未達成のミッションがあってもPDFを作れます。</p><p>学校のChromebookで公開URLとPDFの書き込み・保存を事前に確認してください。生徒の記録は各端末に保存され、外部へ送信されません。</p></details><details><summary>科学とゲームの設定</summary><p>宇宙の歴史は科学に基づく再現、未来は予測です。時代旅行・光速移動・安全な採集は架空技術です。物体を光速まで加速することはできません。</p><p>天体・試料の画像は生成したイメージです。宇宙初期の色や構造も理解を助けるための表現です。天体の表示サイズや画像の縮尺は場所によって異なります。「太陽系360°」では太陽と8つの惑星を3Dで配置し、裏側や上下にも回り込めます。軌道上の位置と惑星の表面には画像を使い、自転・公転の動きを再現しています。実際の日時の天体配置ではありません。歴史の調査地点も360度で観察できます。過去・未来の惑星配置は推定を含む学習モデルです。</p><p>太陽は赤色巨星の後、白色矮星になります。超新星爆発やブラックホールになる星とは区別しています。</p><ul class="sources"><li><a href="https://science.nasa.gov/universe/overview/" target="_blank" rel="noopener noreferrer">NASA：宇宙の歴史</a></li><li><a href="https://spaceplace.nasa.gov/solar-system-formation/en/" target="_blank" rel="noopener noreferrer">NASA：太陽系の形成</a></li><li><a href="https://science.nasa.gov/earth/facts/" target="_blank" rel="noopener noreferrer">NASA：地球</a></li><li><a href="https://science.nasa.gov/sun/facts/" target="_blank" rel="noopener noreferrer">NASA：太陽</a></li><li><a href="https://science.nasa.gov/resource/the-life-cycle-of-a-sun-like-star-annotated/" target="_blank" rel="noopener noreferrer">NASA：太陽のような星の一生</a></li></ul></details>`);}
async function animate(label,duration=1300){$('#transition-label').textContent=label;$('#transition').hidden=false;try{await new Promise(resolve=>{const finish=()=>{clearTimeout(timer);skipAnimation=null;resolve();};const timer=setTimeout(finish,state.reducedMotion?40:duration);skipAnimation=finish;});}finally{$('#transition').hidden=true;}}
async function travel(id){const scene=sceneById(id);if(!scene||busy)return;flight?.stop();busy=true;closeModal();try{await Promise.all([loadImage(scene.image),animate(`${scene.name}へ、時間移動中`)]);state.currentScene=id;state.flightMode='history';if(id==='white-dwarf')state.whiteDwarfView='artwork';state.camera=defaultCamera();state.historySolar={...defaultSolar(id),timeScale:worldState().timeScale||10};save();view='ship';render();window.scrollTo({top:0,behavior:'instant'});}catch(e){toast(e.message,true);}finally{busy=false;}}
async function observe(){if(busy)return;flight?.stop();if(state.flightMode==='history'&&(usesDwarfArtwork(state)||isSceneSubject(state.currentScene,worldState())))commit(()=>{if(!state.observed.includes(state.currentScene))state.observed.push(state.currentScene);});if(usesDwarfArtwork(state))showArtworkObservation();else showSolarObservation();}
async function photograph(){if(busy)return;flight?.stop();busy=true;try{if(usesDwarfArtwork(state))await loadImage(sceneById(state.currentScene).image);else await rendererReady;$('.cockpit')?.classList.add('flash');sound('shutter');await delay(state.reducedMotion?30:400);commit(()=>{const id=`p-${crypto.randomUUID()}`;recordWorldPhoto(state,id);},'写真をアルバムに保存しました');}catch(e){toast(e.message,true);}finally{busy=false;}}
function chooseSample(){if(state.flightMode==='solar'){showSolarObservation(true);return;}const scene=sceneById(state.currentScene);if(scene.extraSample){openModal('採集するものを選ぶ',`<div class="sample-choices">${[scene.sample,scene.extraSample].map(id=>{const s=sampleById(id);return `<button class="sample-choice" data-action="collect" data-sample="${s.id}"><img src="${s.image}" alt=""><strong>${rubyText(s.name)}</strong><span>${rubyText(s.method)}</span>${hasSample(state,s.id)?'<small>採集済み</small>':''}</button>`;}).join('')}</div><p class="fine">氷は太陽から遠い低温域に探査ドローンを送って採集します。</p>`);}else collectSample(scene.sample);}
async function collectSample(id){if(busy)return;const sample=sampleById(id);if(!sample||sample.scene!==state.currentScene)return;if(hasSample(state,id)){showDetail(`sample:${id}`);return;}busy=true;closeModal();try{await loadImage(sample.image||sceneById(sample.scene).image);await animate(sample.kind==='data'?'観測装置で、光の記録を取得中':'探査ドローンが、試料を回収中',1400);commit(()=>recordSample(state,id),`${sample.name}をコレクションに追加しました`);showDetail(`sample:${id}`);}catch(e){toast(e.message,true);}finally{busy=false;}}
async function preview(key){const item=items(state).find(i=>i.key===key);if(!item)return;openModal('発表ページのプレビュー','<p class="muted">ページを作成しています…</p>',true);const request=modalRevision;try{const page=await renderSlide(item,state.titles[key]||item.name,state.selected.indexOf(key)+1,state.selected.length,1.6);if(modal.open&&request===modalRevision){$('.modal-body').innerHTML='<div class="pdf-preview"></div><p class="fine">PDFを保存した後、Chromebookの描画ツールで白い欄に書き込めます。</p>';$('.pdf-preview').append(page);}}catch(e){if(request===modalRevision){toast(e.message,true);closeModal();}}}
async function exportPdf(){const selected=selectedItems();if(!selected.length||busy)return;busy=true;const btn=$('[data-action="export-pdf"]');btn.disabled=true;try{const blob=await createPdf(selected,state.titles,(n,total)=>{btn.textContent=`PDFを作成中 ${n} / ${total}`;});commit(()=>{state.pdfCreated=true;});showDownload(blob,'わたしの宇宙調査.pdf','発表PDFができました','PDFをダウンロード','保存したPDFをChromebookの描画ツールで開き、白い欄に書き込んでください。');}catch(e){toast(e.message||'PDFを作成できませんでした。',true);}finally{busy=false;render();}}
function showDownload(blob,filename,title,label,note){if(latestDownloadUrl)URL.revokeObjectURL(latestDownloadUrl);latestDownloadUrl=URL.createObjectURL(blob);openModal(title,"<p>"+esc(note)+"</p><a class='button wide' href='"+latestDownloadUrl+"' download='"+esc(filename)+"'>"+icon('download')+label+"</a><p class='fine'>ファイルの保存先を確認してください。</p>");}function exportData(){showDownload(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'時空調査船-探検データ.json','探検データを持ち出す','探検データをダウンロード','このファイルを保存すると、次の授業や別の端末で探検の続きができます。');}
async function importData(file){if(!file)return;try{if(file.size>2*1024*1024)throw new Error('ファイルが大きすぎます。探検データのJSONファイルを選んでください。');pendingImport=validateState(JSON.parse(await file.text()));openModal('探検データを読み込む',`<p>写真${pendingImport.photos.length}枚、サンプル${pendingImport.samples.length}点の探検データです。</p><p>今の探検記録が、このファイルの記録に置き換わります。</p><div class="row wrap">${button('export-data','今の記録を保存','download')}${button('confirm-import','このデータを読み込む','upload','')}</div>`);}catch(e){toast(e instanceof SyntaxError?'探検データのJSONファイルを読み込んでください。':e.message,true);}finally{$('#import-file').value='';}}

// Interaction routing. All rendered user input is escaped or assigned via textContent.
document.addEventListener('click',async e=>{const el=e.target.closest('button,[data-view]');if(!el)return;if(el.id==='skip-transition'){skipAnimation?.();return;}if(el.dataset.action==='close'){closeModal();return;}if(busy)return;if(el.dataset.view){navigate(el.dataset.view);return;}if(el.dataset.filter){filter=el.dataset.filter;render();return;}const a=el.dataset.action,key=el.dataset.key;try{switch(a){
case 'dwarf-explore':case 'dwarf-artwork':flight?.stop();state.whiteDwarfView=a==='dwarf-explore'?'explore':'artwork';save();closeModal();navigate('ship');break;
case 'enter-solar':flight?.stop();state.flightMode='solar';save();closeModal();navigate('ship');break;case 'enter-history':flight?.stop();state.flightMode='history';save();closeModal();navigate('ship');break;case 'ship':closeModal();navigate('ship');break;case 'collection':closeModal();navigate('collection');break;case 'presentation':closeModal();navigate('presentation');break;
case 'curriculum':showCurriculum(el.dataset.lesson);break;case 'lesson-travel':await goToLesson(el.dataset.lesson);break;
case 'album':filter='photo';navigate('collection');break;case 'samples':filter='sample';navigate('collection');break;case 'missions':showMissions();break;case 'shelf':showShelf();break;case 'help':showHelp();break;
case 'observe':await observe();break;case 'photograph':await photograph();break;case 'sample':chooseSample();break;case 'collect':await collectSample(el.dataset.sample);break;case 'travel':await travel(el.dataset.scene);break;case 'next':navigate('time');break;case 'next-task':{const next=nextTask(state);if(next)await travel(next.task.scene);else navigate('presentation');break;}
case 'choose-mission':state.activeMission=el.dataset.mission;save();closeModal();navigate('time');break;case 'detail':showDetail(key);break;case 'toggle-select':toggleSelect(key);break;case 'detail-select':toggleSelect(key);showDetail(key);break;
case 'confirm-delete-photo':{const photo=state.photos.find(p=>`photo:${p.id}`===key);if(photo)openModal('この写真を削除しますか？',`<p>この写真をアルバムと発表の選択から削除します。使っている比較カードやミッションが未達成に戻る場合があります。</p><p>必要な記録は、先に設定から探検データを保存してください。</p><div class="row wrap">${button('close','キャンセル',null,'subtle')}${button('delete-photo','写真を削除する',null,'danger',`data-key="${key}"`)}</div>`);break;}
case 'delete-photo':if(state.photos.some(p=>`photo:${p.id}`===key)){commit(()=>removePhoto(state,key.slice(6)),'写真を削除しました。新しい写真を撮れます。');closeModal();}break;
case 'recommend-slides':if(!state.selected.length){const keys=recommendedSelection(state);if(keys.length)commit(()=>{state.selected=keys;},`おすすめ${keys.length}枚を選びました。順番や内容は自由に変えられます。`);}break;
case 'make-single':if(!state.selected.includes(key))toggleSelect(key);closeModal();navigate('presentation');break;case 'remove-selected':toggleSelect(key);break;
case 'move-up':case 'move-down':{const i=state.selected.indexOf(key),j=i+(a==='move-up'?-1:1);if(i>=0&&j>=0&&j<state.selected.length){[state.selected[i],state.selected[j]]=[state.selected[j],state.selected[i]];save();render();}break;}
case 'preview':await preview(key);break;case 'export-pdf':await exportPdf();break;case 'export-data':exportData();break;case 'import-data':$('#import-file').click();break;
case 'confirm-import':if(pendingImport){state=pendingImport;pendingImport=null;damagedSave=false;save();closeModal();navigate('ship');toast('探検データを読み込みました');}break;
case 'confirm-reset':openModal('新しい探検を始めますか？',`<p>今の写真・サンプル・称号がリセットされます。続きから遊びたい場合は、先に探検データを保存してください。</p><div class="row wrap">${button('export-data','今の記録を保存','download')}${button('reset','リセットして始める',null,'danger')}</div>`);break;
case 'reset':state=freshState();state.started=true;damagedSave=false;save();closeModal();navigate('ship');toast('新しい探検を始めました');break;
case 'speak':reader.start(readableText(el.closest('[data-reading-panel]')?.querySelector('[data-reading-content]')));break;case 'stop-reading':reader.stop();break;
}}catch(err){toast(err.message||'操作を完了できませんでした。',true);}});
document.addEventListener('input',e=>{if(e.target.dataset.titleKey){state.titles[e.target.dataset.titleKey]=e.target.value.slice(0,32);save();}});
document.addEventListener('change',e=>{if(e.target.dataset.setting){state[e.target.dataset.setting]=e.target.checked;save();document.body.classList.toggle('reduce-motion',state.reducedMotion);}if(e.target.id==='import-file')importData(e.target.files[0]);});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(!busy)navigate('ship');});$('#rank-button').onclick=()=>{if(!busy)showRanks();};$('#settings-button').onclick=()=>{if(!busy)showSettings();};
window.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement){e.target.classList.add('image-failed');e.target.alt='画像を読み込めません。通信を確認してページを開き直してください。';}},true);
setInterval(()=>{if(document.visibilityState==='visible'){state.minutes++;save();const stats=$('#ship-statistics');if(stats)stats.textContent=`写真 ${state.photos.length}枚 ・ サンプル ${state.samples.length}点 ・ 画面表示 ${state.minutes}分`;if(state.minutes===30)toast('画面表示30分。発表に使う記録を選び始めよう。');}},60000);
save();render();

const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[
{name:'read_expedition',title:'探検記録を読む',description:'現在の場所、称号、ミッション達成、収集物を読み取る。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({scene:state.currentScene,flightMode:state.flightMode,solar:state.solar,historySolar:state.historySolar,rank:RANKS[rankIndex(state)],missions:missionProgress(state).map(m=>({id:m.id,complete:m.complete})),records:items(state).map(i=>({key:i.key,name:i.name})),selected:[...state.selected]})},
{name:'open_expedition_view',title:'探検の画面を開く',description:'船内、時代マップ、コレクション、発表の画面を表示する。記録の作成やPDFの保存は行わない。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['ship','time','collection','presentation']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(busy||!input||!['ship','time','collection','presentation'].includes(input.view))throw new Error('表示先を指定してください。');navigate(input.view);return {view};}}
];for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}


function renderSolarShip(){
  const world=worldState(),history=state.flightMode==='history',scene=history?sceneById(state.currentScene):null,era=eraConfig(world.era);
  return `<div class="page ship-page solar-zone"><div class="page-heading"><div><p class="eyebrow">SPACE & TIME · 360° EXPLORATION</p><h1>${scene?rubyText(scene.name):'太陽系を、どこまでも見渡そう。'}</h1></div><div class="row wrap">${button('curriculum','学習ノート 001〜010','info','subtle small')}${history&&scene.id==='white-dwarf'?button('dwarf-artwork','星雲の全景を見る','eye','subtle small'):''}${history?button('enter-solar','現在の太陽系へ','rocket','subtle small'):button('enter-history','時代の調査へ','time','subtle small')}</div></div>
  ${renderMissionGuide()}<section class="cockpit solar-cockpit" aria-label="360度の宇宙を飛行する宇宙船"><div class="solar-window"><canvas class="solar-canvas" tabindex="0" width="1100" height="620" aria-label="360度の宇宙。ドラッグと矢印キーで見回す。WASDとQ/Eで移動。Xで停止。スペースで撮影。"></canvas><span class="solar-target-marker" hidden></span></div><img class="cockpit-overlay" src="assets/cockpit.png" alt="" aria-hidden="true"><div class="scene-label"><span class="location-kicker">${scene?scene.era:'現在の太陽系'} / 360°</span><h2 class="solar-location">観測場所を確認中</h2><p>${scene?scene.tag:'自由航行'}</p></div><span class="scene-tag">${world.era==='early-universe'?'太古の光の再現':'天体の全球を探索'}</span><div class="cockpit-caption solar-bearing">ドラッグで、上下・左右・後ろも見渡そう。</div><div class="view-action">${button('album','アルバム','album','subtle small')}${button('samples','サンプル','collection','subtle small')}</div><div class="cockpit-controls"><button class="command" data-action="observe">${icon('eye')}<span>観察する</span></button><button class="command" data-action="photograph">${icon('camera')}<span>写真を撮る</span></button><button class="command" data-action="sample">${icon('sample')}<span>${history?'サンプル採取':'採集の案内'}</span></button><button class="command" data-view="time">${icon('time')}<span>時代を選ぶ</span></button></div></section>
  <p class="world-era-note">${era.note}</p>${solarControls(world)}
  <div class="ship-bottom"><span id="ship-statistics">写真 ${state.photos.length}枚 ・ サンプル ${state.samples.length}点 ・ 画面表示 ${state.minutes}分</span><div class="row"><button data-action="missions">${icon('target')} 調査ノート</button><button data-action="curriculum">${icon('info')} 学習ノート</button><button data-action="help">${icon('info')} 遊び方</button></div></div></div>`;
}
function showArtworkObservation(){
  const scene=sceneById(state.currentScene),camera={...state.camera};
  openModal(scene.name,`<div class="solar-observation"><canvas width="960" height="540" role="img" aria-label="小さく輝く白色矮星と、周囲に広がったガスの全景"></canvas></div><section data-reading-panel>${readingControls()}<div data-reading-content><p class="detail-meta">${rubyText(scene.era)} / ${rubyText(scene.location)}</p><ul class="facts">${scene.facts.map(f=>`<li>${rubyText(f)}</li>`).join('')}</ul></div></section><div class="row wrap">${button('photograph','今の風景を写真に撮る','camera','')}${button('dwarf-explore','この時代を360°探索','rocket','subtle')}${button('curriculum','授業の内容とつなげる','info','subtle')}</div><p class="fine"><a href="${scene.source}" target="_blank" rel="noopener noreferrer">科学の参考資料（NASA）</a></p>`);
  const c=$('.solar-observation canvas');loadImage(scene.image).then(image=>{if(c?.isConnected)drawPhoto(c.getContext('2d'),image,camera,0,0,c.width,c.height);}).catch(e=>toast(e.message,true));
}
function showSolarObservation(sampling=false){
  const world=worldState(),body=visibleBody(world)||nearestBody(world.position,world),history=state.flightMode==='history',scene=history?sceneById(state.currentScene):null;
  const distance=body?length(sub(world.position,body.position))*AU_KM:0,era=eraConfig(world.era);
  const facts=[...(scene&&isSceneSubject(scene.id,world)?scene.facts:[]),...(body?[body.fact]:[]),...(body?.rotationDays?[`自転周期は約${Math.abs(body.rotationDays).toFixed(2)}日。自転の観察で回る様子を確かめよう。`]:[]),...(body?.orbitDays?[`公転周期は約${body.orbitDays.toFixed(1)}日。${body.parent&&body.parent!=='sun'?'親の惑星':'太陽'}の周りを回ります。`]:[])];
  openModal(sampling?'採集の案内':`${body?body.name:era.label}を観察`,`${sampling?'':'<div class="solar-observation"><canvas width="960" height="540" role="img" aria-label="現在の宇宙船からの風景"></canvas></div>'}<section data-reading-panel>${readingControls()}<div data-reading-content>${sampling?`<p>${rubyText('時代の調査地点で、探査ドローンによる試料採取や光の記録ができます。自由飛行では天体の全球を好きな方向から撮影しましょう。')}</p>`:''}<p class="detail-meta">${rubyText(era.label)}${body?` / ${body.name}の中心まで約${Math.round(distance).toLocaleString('ja-JP')} km`:''}</p><ul class="facts">${facts.map(f=>`<li>${rubyText(f)}</li>`).join('')}</ul><p>${rubyText(era.note)}</p></div></section><div class="row wrap">${button('photograph','今の方向を写真に撮る','camera','')}${button('curriculum','授業の内容とつなげる','info','subtle')}${sampling?button('travel','誕生期の地球で岩石を採る','sample','subtle','data-scene="young-earth"')+button('travel','太陽系のはじまりでちりを採る','sample','subtle','data-scene="solar-nebula"'):''}</div>${body?`<p class="fine"><a href="${body.source}" target="_blank" rel="noopener noreferrer">科学の参考資料（NASA）</a></p>`:''}`);
  const c=$('.solar-observation canvas'),snapshot=JSON.parse(JSON.stringify(world));if(c){c.height=Math.round(c.width/(snapshot.aspect||16/9));}if(c)rendererReady.then(()=>{if(c.isConnected)drawSolarPhoto(c.getContext('2d'),snapshot,0,0,c.width,c.height);}).catch(e=>toast(e.message,true));
}
function showCurriculum(id){
  const selected=LESSONS.find(l=>l.id===id)||LESSONS[0];
  openModal('宇宙の学習ノート 001〜010',`<p class="muted">授業の言葉を確かめて、宇宙船の窓から探してみよう。</p><div class="lesson-layout"><nav class="lesson-nav" aria-label="学習する単元">${LESSONS.map(l=>`<button data-action="curriculum" data-lesson="${l.id}" aria-current="${l.id===selected.id?'page':'false'}"><span>${l.id}</span>${rubyText(l.title)}</button>`).join('')}</nav><article class="lesson-content" data-reading-panel>${readingControls()}<div data-reading-content><p class="eyebrow">LESSON ${selected.id}</p><h3>${rubyText(selected.title)}</h3><p>${rubyText(selected.summary)}</p><div class="lesson-keywords">${selected.keywords.map(k=>`<span>${rubyText(k)}</span>`).join('')}</div><div class="lesson-figure">${renderLessonFigure(selected.id)}</div><ul class="facts">${selected.facts.map(f=>`<li>${rubyText(f)}</li>`).join('')}</ul>${selected.details?.length?`<details><summary>もう少し知る</summary>${selected.details.map(d=>`<h4>${rubyText(d.title)}</h4><p>${rubyText(d.text)}</p>`).join('')}</details>`:''}<div class="observation-question"><strong>${rubyText(selected.question)}</strong></div><p>${rubyText(selected.activity)}</p>${button('lesson-travel','この内容を観察しに行く','rocket','','data-lesson="'+selected.id+'"')}<p class="fine">授業プリント No.${selected.id} に対応。図は学習用の模式図です。</p></div></article></div>`,true);
}
async function goToLesson(id){
  const lesson=LESSONS.find(l=>l.id===id);if(!lesson)return;
  if(lesson.scene==='present'||lesson.scene==='solar-system'){closeModal();state.flightMode='solar';state.solar={...defaultSolar(),timeScale:worldState().timeScale||10};}
  else await travel(lesson.scene||'earth');
  const world=worldState(),body=bodyById(lesson.target,world);
  if(body){world.target=body.id;world.position=approachPosition(body);world.orientation=lookAt(sub(body.position,world.position));}
  save();navigate('ship');toast(lesson.activity);
}

function recordScene(item){
  const scene=sceneById(item.scene),snapshot=item.record.solar;
  if(!snapshot)return scene;
  const era=eraConfig(snapshot.era),body=bodyById(snapshot.subject,snapshot);
  return {...scene,era:era.label,location:body?.name||'宇宙の全天',summary:body?.fact||era.note};
}
