// Visible pages are only a view onto the full collection. They never trim records.
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function pageWindow(total,page,size){
  const pages=Math.max(1,Math.ceil(total/size)),index=Math.max(0,Math.min(pages-1,Math.trunc(page)||0));
  return {index,pages,start:index*size,end:Math.min(total,(index+1)*size)};
}
export function collectionPageSize(width,height){return (width>=1200?4:width>=700?3:2)*(height>=550?2:1);}
export function pager(action,index,pages,label='ページ'){
  return `<nav class="screen-pager" aria-label="${label}送り"><button class="button subtle small" data-action="${action}" data-page="${index-1}" ${index===0?'disabled':''}>← 前へ</button><span role="status">${index+1} / ${pages} ${label}</span><button class="button subtle small" data-action="${action}" data-page="${index+1}" ${index>=pages-1?'disabled':''}>次へ →</button></nav>`;
}
export function mapView({scenes,chosen,ruby,button}){
  return `<div class="page compact-page time-page"><header class="compact-heading"><h1>どの時代へ行く？</h1>${button('ship','探検に戻る','ship','subtle small')}</header><div class="time-layout"><nav class="time-choices" aria-label="調査する時代">${scenes.map(s=>`<button data-action="map-choice" data-scene="${s.id}" aria-pressed="${s.id===chosen.id}"><span>${s.number}</span><div><strong>${ruby(s.name)}</strong><small>${s.era}</small></div></button>`).join('')}</nav><section class="time-preview"><img src="${chosen.image}" alt="${esc(chosen.name)}の想像図"><div><span class="era">${chosen.era}</span><h2>${ruby(chosen.name)}</h2><p>${chosen.summary}</p>${button('travel','この時代へ移動','rocket','',`data-scene="${chosen.id}"`)}</div></section></div><p class="compact-note">年代は自動では変わりません。風景は観測・研究を参考にした模型です。</p></div>`;
}
export function collectionView({list,window:page,filter,counts,selectedCount,card,button,icon,secretButton=''}){
  return `<div class="page compact-page collection-page"><header class="compact-heading"><h1>コレクション</h1>${button('presentation',`発表に使う ${selectedCount}件`,'pdf','small')}</header><div class="collection-tabs" aria-label="コレクションの種類">${[['photo','写真','camera'],['sample','サンプル','sample'],['compare','比較カード','compare']].map(([id,name,ic])=>`<button data-filter="${id}" aria-pressed="${filter===id}" class="${filter===id?'active':''}">${icon(ic)}${name}<span>${counts[id]}</span></button>`).join('')}${filter==='sample'?button('shelf','展示棚','collection','subtle small'):''}${secretButton}</div>${list.length?`<div class="record-grid compact-record-grid">${list.slice(page.start,page.end).map(card).join('')}</div>`:`<div class="empty"><h2>${filter==='compare'?'2つの時代を撮影すると比較カードが完成します。':'観察して、記録を持ち帰ろう。'}</h2>${button('ship','探検へ','ship','')}</div>`}${pager('collection-page',page.index,page.pages)}<p class="compact-note">記録を開くと、説明・年代・観測値を確認できます。${filter==='photo'&&counts.photo>=60?'写真は60枚まで。詳細画面から不要な写真を整理できます。':''}</p></div>`;
}
export function presentationView({selected,index,titles,button,icon,kindName,recommendedCount}){
  const item=selected[index],total=selected.length;
  if(!item)return `<div class="page compact-page presentation-page"><header class="compact-heading"><h1>発表をつくる</h1>${button('collection','記録を選ぶ','collection','subtle small')}</header><div class="empty"><h2>どの発見を伝えよう？</h2><p>コレクションで「発表に使う」を選びます。まずは3枚が目安です。</p>${recommendedCount?button('recommend-slides',`おすすめ${recommendedCount}枚を選ぶ`,'star',''):''}</div></div>`;
  return `<div class="page compact-page presentation-page"><header class="compact-heading"><h1>発表をつくる <small>${total}枚</small></h1><div class="row">${button('collection','記録を追加','collection','subtle small')}${button('export-pdf','PDFを作成','download','small')}</div></header><div class="slide-workspace"><section class="slide-editor"><span class="badge">${index+1}枚目 / ${total}枚</span><label for="slide-title">${kindName(item.kind)}の見出し</label><input id="slide-title" data-title-key="${item.key}" maxlength="32" value="${esc(titles[item.key]||item.name)}"><p class="fine">白い欄は、保存したPDFにChromebookの描画ツールで手書きします。</p><div class="slide-order"><button class="button subtle small" data-action="move-up" data-key="${item.key}" ${index===0?'disabled':''}>${icon('up')} 前の順番へ</button><button class="button subtle small" data-action="move-down" data-key="${item.key}" ${index===total-1?'disabled':''}>${icon('down')} 後の順番へ</button>${button('remove-selected','発表から外す','close','subtle small',`data-key="${item.key}"`)}</div></section><section class="inline-slide" aria-label="発表ページのプレビュー" data-slide-preview="${item.key}"><p role="status">ページを作成しています…</p></section></div>${pager('presentation-page',index,total,'枚目')}</div>`;
}
